### PR TITLE
Update spawn_turtlebot.launch.py

### PR DESCRIPTION
**Pull request by ahtsan**
Changing default value for turtlebot3_model to `waffle_pi` so as to be consistent with `ros1`. Additionally it got a camera.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mm318** [comment]
Did we have some discussion where some (or all) of the sample applications that use this package require that the `TURTLEBOT3_MODEL` environment variable must be set anyways? Is there any case where this package is being used and the `TURTLEBOT3_MODEL` environment variable doesn't need to be specified for some reason? What I am thinking is maybe we should not have a default value at all, and the launch file should error out if the `TURTLEBOT3_MODEL` environment variable is not set.

**Comment by ahtsan** [comment]
I think both hello-world-sample-app and cloudwatch-sample-app requires `TURTLEBOT3_MODEL` to be set specifically. Not sure about 1-click.

**Comment by mm318** [comment]
Also, whether we are changing the default value or removing the default value, let's bump the minor version in the `package.xml`:
```xml
  <version>2.1.0</version>
```

**Review by mm318 — APPROVED** [review]

**Comment by mm318** [comment]
I'll approve and merge this pull request on the grounds that this will make the behavior of ROS2 version of this package match that of the [ROS1 version](https://github.com/aws-robotics/turtlebot3-description-reduced-mesh/blob/a39600ccfc3590afd8828ba652d3babbbf878cf0/launch/spawn_turtlebot.launch#L3).

**Pull request merged**
